# Generated by Django 4.2.3 on 2023-08-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('employees_number', models.PositiveIntegerField()),
                ('logo', models.ImageField(null=True, upload_to='companies/logo')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Expirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'expirience',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('intern', 'intern')])),
                ('expirience', models.CharField(choices=[('Without experience', 'Without experience')])),
                ('min_salary', models.PositiveIntegerField(null=True)),
                ('max_salary', models.PositiveIntegerField(null=True)),
                ('attachment', models.FileField(null=True, upload_to='vacancies/attachments')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', related_query_name='vacancy', to='core.company')),
            ],
            options={
                'db_table': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='VacancyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy')),
            ],
            options={
                'db_table': 'vacancies_tags',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(through='core.VacancyTag', to='core.tag'),
        ),
    ]
