# Generated by Django 4.2.2 on 2023-07-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('employeer_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INTERN', 'INTERN'), ('JUNIOR', 'JUNIOR'), ('MIDDLE', 'MIDDLE'), ('SENIOR', 'SENIOR')], max_length=10)),
                ('expirience', models.CharField(max_length=30)),
                ('min_salary', models.PositiveIntegerField(null=True)),
                ('max_salary', models.PositiveIntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', related_query_name='vacancy', to='core.company')),
            ],
        ),
    ]
