# Generated by Django 4.2.3 on 2023-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='attachment',
            field=models.FileField(null=True, upload_to='vacancies/attachments'),
        ),
    ]
