# Generated by Django 4.2.2 on 2023-07-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_defaults_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='employeer_number',
            new_name='employees_number',
        ),
    ]
