# Generated by Django 4.2.2 on 2023-07-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_employeer_number_company_employees_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='Test value', max_length=30),
            preserve_default=False,
        ),
    ]
