# Generated by Django 4.2.2 on 2023-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'expirience',
            },
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='expirience',
            field=models.CharField(max_length=50),
        ),
    ]
